CORSIKA:
  RUNNR: 1
  EVTNR: 1
  ESLOPE: -2.0
  PRMPAR: 1
  VIEWCONE: 0.0 1.5

  OBSLEV: 2158.E2
  ATMOSPHERE: 36 Y
  MAGNET: 30.576 23.571
  ARRANG: -5.3195
  CSCAT:  1  0.  0.

  FIXHEI:  0. 0
  FIXCHI:  0.
  TSTART:  T
  ECUTS:   0.3  0.1  0.020  0.020
  MUADDI:  F
  MUMULT:  T
  LONGI:   T  20.  F  F
  MAXPRT:  0
  ECTMAP:  1.E6
  STEPFC:  1.0

  CERSIZ:  5.
  CERFIL:  F
  CWAVLG:  240.  900.

  DEBUG:   F  6  F  1000000
  DIRECT:  /dev/null

  IACT SPLIT_AUTO: 8M
  IACT IO_BUFFER: 1000MB
  IACT MAX_BUNCHES: 10000000

ShowerSimulation:
  diameter: 25
  event_number: 1
  zenith_scaling: True
  min_events: 1000
  scaling_index: -1.5

  altitude: 70
  azimuth:
        - 0
  energy_bins:
        - 7.94328235e-01

  core_bins:
            - 0
            - 25
            - 50
            - 75
            - 100
            - 125
            - 150
            - 175
            - 200
            - 250
            - 300
            - 350
            - 400
            - 450
            - 500
            - 600
            - 700

  rotation_angle:
            - 0

TelescopeSimulation:
  config_name: "LST"
  config_file: "cfg/CTA/CTA-PROD4-LST.cfg"
  atmosphere: "atm_trans_2158_1_10_0_0_0.dat"
  sim_telarray_directory: "/pbs/home/t/tarmstro/Software/corsikaSimtelarray/d2020-02-12"
  extra_options: ""
  optical_efficiency: 1

